### ISSUE TITLE
Protected sites

### ISSUE THREAD

**Issue by davidhedlund** [sblask/webextension-simple-form-fill#15] opened 2017-09-07 16:53 UTC
Some websites (often banks and governments websites like healthcare), told me that they protect their forms by not allowing form filling programs.

Either:
* Simple Form Fill will not show any lines, the only visible line will be "Preferences".
* Or the data from Simple Form Fill will not functioning, you will have to manually remove the last character that Simple Form Fill added to a form, and then type i back with your keyboard.

Can you please mention this on https://addons.mozilla.org/en-US/firefox/addon/simple-form-fill/

**Comment by davidhedlund** [comment] 2017-09-07 16:59
Or the data from Simple Form Fill will not functioning, you will have to manually remove the last character that Simple Form Fill added to a form, and then type i back with your keyboard.

**Comment by davidhedlund** [comment] 2017-09-07 17:02
It it possible to add a line "Simple Form Fill was blocked" when you try to use Simple Form Fill if it cannot add anything?

**Comment by sblask** [comment] 2017-09-07 21:36
I have no idea what you are talking about, you'll need to at least give me an example. The only problem I ever had was a mismatch in expected format and item so that when the item is chosen, it won't be added. Nothing much I can do there if I don't want to write a validator for all possible formats. Might even be a bug in Firefox. I'd expect to always be able to add a value to a form field, be it by Simple Form Fill or copy paste. A warning would be in order but doing a copy paste and nothing happens is very irritating.

**Comment by davidhedlund** [comment] 2017-09-07 22:02
# Example
Visit https://www.1177.se/Vasterbotten/ and follow these steps:

* Click on "Logga in" (top right):
![screenshot from 2017-09-07 23 52 25](https://user-images.githubusercontent.com/6416073/30186948-fb5e49b2-9427-11e7-94fa-978fd4d7bd54.png)

* Click on "Logga in":
![screenshot from 2017-09-07 23 53 01](https://user-images.githubusercontent.com/6416073/30186987-1d761e62-9428-11e7-844d-4e36d6630f5a.png)

* Scroll down a bit and click on "Lösenord och SMS":
![screenshot from 2017-09-07 23 53 23](https://user-images.githubusercontent.com/6416073/30187000-2b01f236-9428-11e7-9171-b3d28798dc0f.png)


* On this page i cannot use Simple Form Fill to fill the "Personnummer" field:
![screenshot from 2017-09-08 00 00 08](https://user-images.githubusercontent.com/6416073/30187163-bf90477c-9428-11e7-8adc-e45807449300.png)

Simple Form Fill is hidden when I capture the screenshots but I cannot use it, please try it yourself.

**Comment by davidhedlund** [comment] 2017-09-07 22:04
1177.se as mentioned above is the official healthcare site used in Sweden for all citizens.

**Comment by sblask** [comment] 2017-09-07 22:26
I think this is actually a duplicate of https://github.com/sblask/webextension-simple-form-fill/issues/12

**Closed by sblask** 2017-09-07 22:26 UTC

**Comment by davidhedlund** [comment] 2017-09-08 06:21
@sblask No it is not. "Personnummer" (Swedish) is translated to "Personal number" which is equal to Social Security number in the US. Can you please re-open?

**Comment by sblask** [comment] 2017-09-08 08:37
I know what it means, I live in Sweden. But it doesn't have anything to do with what appears in the context menu. They actually changed the input type to text(it used to be tel and number I think) now, so Simple Form Fill doesn't have any problem with it.

**Comment by davidhedlund** [comment] 2017-09-08 08:41
> I know what it means, I live in Sweden.
Jag bor i Västerbotten. =)

The personal number field for swedbank.se cannot be used with Simple Form Fill either, can you please have a look?

**Comment by sblask** [comment] 2017-09-08 10:38
Input type `tel` so it's the same Firefox bug.

**Comment by davidhedlund** [comment] 2017-09-08 10:46
For both 1177.se _and_ swedbank.se?

**Comment by davidhedlund** [comment] 2017-09-08 10:51
Thanks, yes I see that 1177.se is using ```<input id="uid" name="uid" type="tel" value="">```

What about swedbank.se (I cannot see their page source)?

**Comment by davidhedlund** [comment] 2017-09-08 10:53
Also, cannot my phone number that I've added to Simple Form Fill is not visible, shouldn't it be that for ```type="tel"```?

**Comment by sblask** [comment] 2017-09-08 19:39
It's a bug in Firefox. From Simple Form Fill's side, everything should always be visible for input fields.
